### ISSUE TITLE
Possible permission issue - accessing posts 

### ISSUE THREAD

**Issue by Samelot** [marcokstephen/internet-forum#1]
Let me first say thanks, for this informative, well orchestrated tutorial. It has been a great resource to learn php and mysql, touching up on important aspects of both languages. 

While reading this: 

> Post Layouts
> 
> (This page is very similar to index.php and topics.php, so my explanation will be fairly brief. As always, looking at the code will be very beneficial to you understanding what is happening.) We begin posts.php by creating two variables which we populate with the board ID and topic ID. Once again, we must check permissions to see if the user is allowed to view the board, so we create an SQL query using the board ID that we got from the URL. The reason that we must check the permissions at each step in the process is because otherwise, it would be easy for a user to bypass one of our checks by simply entering a URL. The permission system is also why we must search for posts in topics using both the board ID and topic ID. We _could_ use just the topic ID in our SQL query, but then there would be no way to determine if a user had permission to view that topic or not! By using both board ID and topic ID in our search, we can link these two variables, and only display the topic if the user has permission to see it.

I felt compelled to change some code to better understand how the permissions process works. In the process of doing so I think I may have found a possible bug in the post.php document.
- In posts.php, if I remove:
  
  ```
  $bid = mysql_real_escape_string($_GET['bid']);
  $tid = mysql_real_escape_string($_GET['tid']);
  ```
  
  I am still able to access the topic's posts at url:
  
  ```
  http://localhost:8888/internet-forum/posts.php?bid=1&tid=1
  ```
  
  Strangely, I do see that the topic name disappears from the page.
- In topics.php, if I remove:
  
  ```
  $bid = mysql_real_escape_string($_GET['bid']);
  ```
  
  As expected, I am no longer able to access the topic at url:
  
  ```
  http://localhost:8888/internet-forum/topics.php?bid=1
  ```
  
  I get the "404 topic not found" error.

**Comment by marcokstephen** [comment]
Hi! Thanks for the feedback. I haven't gotten a chance to test this, but by glancing at the code I believe I can see why it occurs.

It's sloppy of me, but if you look at <a href="https://github.com/marcokstephen/internet-forum/blob/db3bfe5df9f22526297d325a371f620c5a4abef4/posts.php">posts.php</a>, even though I declare the variable _<B>$bid = mysql_real_escape_string($_GET['bid']);_</B>, there are other parts of the page where I don't actually use the _<B>$bid</B>_ variable, and instead reference _<B>mysql_real_escape_string($_GET['bid']);</B>_ directly. This is why when you remove the code from the page, some things still appear and some things (like the topic name, where I did in fact use the variable) disappear.

These formatting mistakes don't occur in topics.php, which is why the outcome is different.
Let me know if this doesn't clear it up!

**Comment by marcokstephen** [comment]
I've updated <a href="https://github.com/marcokstephen/internet-forum/blob/master/posts.php">posts.php</a> (the old version can be found <a href="https://github.com/marcokstephen/internet-forum/blob/db3bfe5df9f22526297d325a371f620c5a4abef4/posts.php">here</a>), replacing all occurrences of _<B>mysql_real_escape_string($_GET['bid'])</B>_ with _<B>$bid</B>_, and the same thing for <B>_$tid_</B>. Now, when you make the same test, you should get the expected results (same results as when you tested topics.php).

**Comment by Samelot** [comment]
yep, that certainly did the trick.. Thanks
